import { CONGESTION_COLOR, CONGESTION_LVL, CONGESTION_TXT } from '../../../constant';

export const CONGESTION_DESC_INFO = [
  {
    id: CONGESTION_LVL.VERY_BAD,
    color: CONGESTION_COLOR.VERY_BAD,
    title: CONGESTION_TXT.VERY_BAD,
  },
  {
    id: CONGESTION_LVL.BAD,
    color: CONGESTION_COLOR.BAD,
    title: CONGESTION_TXT.BAD,
  },
  {
    id: CONGESTION_LVL.NORMAL,
    color: CONGESTION_COLOR.NORMAL,
    title: CONGESTION_TXT.NORMAL,
  },
  {
    id: CONGESTION_LVL.GOOD,
    color: CONGESTION_COLOR.GOOD,
    title: CONGESTION_TXT.GOOD,
  },
  {
    id: CONGESTION_LVL.CLOSED,
    color: CONGESTION_COLOR.CLOSED,
    title: CONGESTION_TXT.CLOSED,
  },
];
